import {
  assembleAnswer,
  caseChunksOf,
  legalChunksOf,
  precedentChunksOf,
  unavailableAnswer,
} from './answer.assembler';
import { AIAnswer, AIGenerateInput, AIProvider, AISummarizeInput } from './types';
import { answerCoverage, isDeicticQuery } from './relevance';

const MOCK_WARNINGS = ['Development mock provider. No external LLM is connected unless AI_PROVIDER=openai or AI_PROVIDER=gemini with a backend API key is configured.'];

const factLines = (chunks: ReturnType<typeof caseChunksOf>, label: string): string[] =>
  chunks.map((chunk) => `${label} ${chunk.documentName} (${chunk.pageOrSection}): ${chunk.text.slice(0, 400)}`);

const buildExplanation = (
  caseContext: ReturnType<typeof caseChunksOf>,
  legalContext: ReturnType<typeof legalChunksOf>,
  userQuery: string,
  operation: AIAnswer['operation'],
): string => {
  const caseDocs = [...new Set(caseContext.map((c) => c.documentName))];
  const legalDocs = [...new Set(legalContext.map((c) => c.documentName))];
  const caseText = caseContext.map((c) => c.text).filter(Boolean);
  const legalText = legalContext.map((c) => c.text).filter(Boolean);

  const parts: string[] = [];
  parts.push(`Response to: "${userQuery}"`);

  if (caseDocs.length > 0) {
    parts.push(`Based on ${caseDocs.length} case source(s): ${caseDocs.join(', ')}.`);
    if (caseText.length > 0) {
      parts.push(`Key content from case records: ${caseText.join(' ').slice(0, 600)}`);
    }
  } else {
    parts.push('No case-evidence sources were retrieved for this query.');
  }

  if (legalDocs.length > 0) {
    parts.push(`Legal authorities consulted: ${legalDocs.join('; ')}.`);
    if (legalText.length > 0) {
      parts.push(`Relevant legal text: ${legalText.join(' ').slice(0, 600)}`);
    }
  }

  if (operation === 'research' || operation === 'compare_authorities') {
    parts.push('A retrieved judgment is not automatically binding precedent.');
  }

  parts.push('Generated by the development mock provider.');
  return parts.join(' ');
};

export class MockAIProvider implements AIProvider {
  async generateAnswer(input: AIGenerateInput): Promise<AIAnswer> {
    return this.compose(input, input.operation ?? 'answer', input.userQuery);
  }

  async summarize(input: AISummarizeInput): Promise<AIAnswer> {
    return this.compose(
      { ...input, userQuery: 'Summarize the authorized case records.' },
      'summarize',
      'Summarize',
    );
  }

  async analyzeEvidence(input: AIGenerateInput): Promise<AIAnswer> {
    return this.compose(input, 'analyze_evidence', input.userQuery);
  }

  async research(input: AIGenerateInput): Promise<AIAnswer> {
    return this.compose(input, input.operation ?? 'research', input.userQuery);
  }

  private compose(
    input: AIGenerateInput | AISummarizeInput,
    operation: AIAnswer['operation'],
    userQuery: string,
  ): AIAnswer {
    const caseContext = caseChunksOf({
      context: 'context' in input ? input.context : [],
      caseContext: input.caseContext,
    });
    const legalContext = legalChunksOf({ legalContext: input.legalContext });
    const precedentContext = precedentChunksOf({ precedentContext: input.precedentContext });
    if (caseContext.length === 0 && legalContext.length === 0 && precedentContext.length === 0) {
      return unavailableAnswer(operation, 'MOCK', MOCK_WARNINGS);
    }

    // Grounding coverage check: the mock can only restate retrieved sources, so a
    // question whose distinctive terms appear nowhere in them must be reported as
    // insufficient evidence rather than answered by invention (Phases 11/12).
    // Deictic questions ("Summarize this case.") are already authorized-and-
    // retrieved by the case retrieval gate and are exempt.
    const combinedText = [...caseContext, ...legalContext, ...precedentContext].map((chunk) => chunk.text).join('\n');
    const coverage = isDeicticQuery(userQuery) ? null : answerCoverage(userQuery, combinedText);
    if (coverage?.decision === 'insufficient') {
      return unavailableAnswer(operation, 'MOCK', [
        ...MOCK_WARNINGS,
        `The retrieved sources do not mention: ${coverage.missing.join(', ')}. Insufficient evidence to answer this question.`,
      ]);
    }

    const facts = [
      ...factLines(caseContext, 'Case source fact from'),
      ...factLines(legalContext, 'Legal authority fact from'),
      ...factLines(precedentContext, 'Judicial precedent fact from'),
    ];
    const unsupported = [
      'Do not treat retrieved authorities as automatically binding.',
      'External web search and commercial reporters are not connected.',
      ...(precedentContext.some((c) => c.provenance?.contentCompleteness === 'development-excerpt')
        ? ['Retrieved judicial precedents are development excerpts, not complete official reports.']
        : []),
      ...(coverage?.decision === 'partial' && coverage.missing.length > 0
        ? [`The retrieved sources do not explicitly mention: ${coverage.missing.join(', ')} — the answer may not cover those aspects.`]
        : []),
    ];

    const explanation = buildExplanation(caseContext, legalContext, userQuery, operation);

    const caseSourceLines = facts.filter((line) => line.startsWith('Case'));
    const legalSourceLines = facts.filter((line) => line.startsWith('Legal'));
    const precedentSourceLines = facts.filter((line) => line.startsWith('Judicial'));

    return assembleAnswer({
      operation,
      mode: 'MOCK',
      caseContext,
      legalContext,
      precedentContext,
      facts,
      explanation,
      unsupported,
      warnings: MOCK_WARNINGS,
      userQuery,
      status:
        coverage?.decision === 'partial'
          ? 'partial'
          : caseContext.length > 0 &&
            (operation === 'research' || operation === 'compare_authorities' ? legalContext.length > 0 : true)
            ? 'grounded'
            : 'partial',
      answer: [
        'CASE EVIDENCE:',
        caseSourceLines.length ? caseSourceLines.map((line) => `- ${line}`).join('\n') : '- none retrieved',
        '',
        'LEGAL AUTHORITIES:',
        legalSourceLines.length ? legalSourceLines.map((line) => `- ${line}`).join('\n') : '- none retrieved',
        '',
        'JUDICIAL PRECEDENTS:',
        precedentSourceLines.length ? precedentSourceLines.map((line) => `- ${line}`).join('\n') : '- none retrieved',
        '',
        'Generated explanation:',
        explanation,
        '',
        'Unsupported information:',
        ...unsupported.map((line) => `- ${line}`),
      ].join('\n'),
    });
  }
}
