-- Additive Phase 2 migration. Intentionally not applied by this change.
CREATE TYPE "AuditAction" AS ENUM ('CASE_CREATED','CASE_UPDATED','PARTICIPANT_ADDED','PARTICIPANT_REMOVED','CASE_JUDGE_ASSIGNED','DOCUMENT_UPLOADED','DOCUMENT_VIEWED','DOCUMENT_DOWNLOADED','EVIDENCE_SUBMITTED','EVIDENCE_STATUS_CHANGED','DOCUMENT_ANCHORED','DOCUMENT_VERIFICATION_STARTED','DOCUMENT_VERIFIED','DOCUMENT_REJECTED','DOCUMENT_VERIFICATION_UNAVAILABLE','TAMPER_CHECK_PERFORMED','USER_ROLE_CHANGED','LOGIN','FAILED_LOGIN','LOGOUT');
CREATE TYPE "AuditEntityType" AS ENUM ('CASE','CASE_PARTICIPANT','DOCUMENT','EVIDENCE','BLOCKCHAIN_TRANSACTION','VERIFICATION_RECORD','DOCUMENT_COMPARISON','USER','AUTH_SESSION');
CREATE TYPE "IntegrityStatus" AS ENUM ('VERIFIED','MODIFIED','NOT_ANCHORED','VERIFICATION_UNAVAILABLE','HASH_MISMATCH');
CREATE TYPE "JudicialDecision" AS ENUM ('ACCEPTED','REJECTED');
CREATE TYPE "ComparisonResult" AS ENUM ('UNMODIFIED','TAMPERED','ORIGINAL_NOT_ANCHORED','VERIFICATION_UNAVAILABLE');

ALTER TABLE "Case" ADD COLUMN "createdById" TEXT, ADD COLUMN "assignedJudgeId" TEXT;
CREATE INDEX "Case_createdById_idx" ON "Case"("createdById");
CREATE INDEX "Case_assignedJudgeId_idx" ON "Case"("assignedJudgeId");
ALTER TABLE "Case" ADD CONSTRAINT "Case_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Case" ADD CONSTRAINT "Case_assignedJudgeId_fkey" FOREIGN KEY ("assignedJudgeId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "VerificationRecord" ("id" TEXT NOT NULL,"caseId" TEXT NOT NULL,"documentId" TEXT NOT NULL,"evidenceId" TEXT,"judgeId" TEXT NOT NULL,"integrityStatus" "IntegrityStatus" NOT NULL,"judicialDecision" "JudicialDecision","decisionReason" TEXT,"verifiedHash" TEXT,"currentHash" TEXT,"blockchainTransactionId" TEXT,"blockchainReference" TEXT,"verificationDetails" JSONB,"verifiedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "VerificationRecord_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DocumentComparison" ("id" TEXT NOT NULL,"caseId" TEXT NOT NULL,"originalDocumentId" TEXT NOT NULL,"actorId" TEXT NOT NULL,"blockchainTransactionId" TEXT,"originalHash" TEXT NOT NULL,"candidateHash" TEXT NOT NULL,"result" "ComparisonResult" NOT NULL,"candidateFileName" TEXT,"candidateMimeType" TEXT,"candidateFileSize" INTEGER,"details" JSONB,"comparedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "DocumentComparison_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL,"caseId" TEXT NOT NULL,"actorId" TEXT,"action" "AuditAction" NOT NULL,"entityType" "AuditEntityType" NOT NULL,"documentId" TEXT,"evidenceId" TEXT,"verificationId" TEXT,"comparisonId" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));

CREATE INDEX "AuditLog_caseId_createdAt_idx" ON "AuditLog"("caseId","createdAt"); CREATE INDEX "AuditLog_actorId_createdAt_idx" ON "AuditLog"("actorId","createdAt"); CREATE INDEX "AuditLog_documentId_createdAt_idx" ON "AuditLog"("documentId","createdAt"); CREATE INDEX "AuditLog_evidenceId_createdAt_idx" ON "AuditLog"("evidenceId","createdAt"); CREATE INDEX "AuditLog_caseId_action_createdAt_idx" ON "AuditLog"("caseId","action","createdAt");
CREATE INDEX "VerificationRecord_caseId_verifiedAt_idx" ON "VerificationRecord"("caseId","verifiedAt"); CREATE INDEX "VerificationRecord_documentId_verifiedAt_idx" ON "VerificationRecord"("documentId","verifiedAt"); CREATE INDEX "VerificationRecord_evidenceId_verifiedAt_idx" ON "VerificationRecord"("evidenceId","verifiedAt"); CREATE INDEX "VerificationRecord_judgeId_verifiedAt_idx" ON "VerificationRecord"("judgeId","verifiedAt"); CREATE INDEX "VerificationRecord_caseId_integrityStatus_verifiedAt_idx" ON "VerificationRecord"("caseId","integrityStatus","verifiedAt"); CREATE INDEX "VerificationRecord_caseId_judicialDecision_verifiedAt_idx" ON "VerificationRecord"("caseId","judicialDecision","verifiedAt");
CREATE INDEX "DocumentComparison_caseId_comparedAt_idx" ON "DocumentComparison"("caseId","comparedAt"); CREATE INDEX "DocumentComparison_originalDocumentId_comparedAt_idx" ON "DocumentComparison"("originalDocumentId","comparedAt"); CREATE INDEX "DocumentComparison_actorId_comparedAt_idx" ON "DocumentComparison"("actorId","comparedAt"); CREATE INDEX "DocumentComparison_blockchainTransactionId_idx" ON "DocumentComparison"("blockchainTransactionId");

ALTER TABLE "VerificationRecord" ADD CONSTRAINT "VerificationRecord_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "Case"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "VerificationRecord_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "VerificationRecord_evidenceId_fkey" FOREIGN KEY ("evidenceId") REFERENCES "Evidence"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "VerificationRecord_judgeId_fkey" FOREIGN KEY ("judgeId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "VerificationRecord_blockchainTransactionId_fkey" FOREIGN KEY ("blockchainTransactionId") REFERENCES "BlockchainTransaction"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DocumentComparison" ADD CONSTRAINT "DocumentComparison_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "Case"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "DocumentComparison_originalDocumentId_fkey" FOREIGN KEY ("originalDocumentId") REFERENCES "Document"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "DocumentComparison_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "DocumentComparison_blockchainTransactionId_fkey" FOREIGN KEY ("blockchainTransactionId") REFERENCES "BlockchainTransaction"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "Case"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "AuditLog_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "AuditLog_evidenceId_fkey" FOREIGN KEY ("evidenceId") REFERENCES "Evidence"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "AuditLog_verificationId_fkey" FOREIGN KEY ("verificationId") REFERENCES "VerificationRecord"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "AuditLog_comparisonId_fkey" FOREIGN KEY ("comparisonId") REFERENCES "DocumentComparison"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
